[tools]
atuin = "18.10.0"
chezmoi = "2.68.1"
"github:nushell/nushell" = "0.109.1"
bat = "0.26.1"
helix = "25.07.1"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.8"
zellij = "0.43.1"
"github:topgrade-rs/topgrade" = "16.7.0"
"github:fish-shell/fish-shell" = "4.3.2"
tlrc = "1.12.0"
lazygit = "0.57.0"
lazydocker = "0.24.3"
rust = "1.92.0"
"cargo:pueue" = "4.0.2"
delta = "0.18.2"
gh = "2.83.2"
