[tools]
atuin = "18.10.0"
chezmoi = "2.68.1"
"github:nushell/nushell" = "0.109.1"
bat = "0.26.1"
helix = "25.07.1"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.8"
"github:Nukesor/pueue" = "4.0.2"
zellij = "0.43.1"
"github:topgrade-rs/topgrade" = "16.7.0"
"github:fish-shell/fish-shell" = "4.3.2"
tlrc = "1.12.0"
