[tools]
atuin = "18.12.1"
chezmoi = "2.69.4"
bat = "0.26.1"
helix = "25.07.1"
starship = "1.24.2"
vivid = "0.10.1"
zoxide = "0.9.9"
zellij = "0.43.1"
"github:topgrade-rs/topgrade" = "16.9.0"
lazygit = "0.59.0"
lazydocker = "0.24.4"
rust = "1.93.1"
"cargo:pueue" = "4.0.2"
delta = "0.18.2"
gh = "2.87.0"
"aqua:fish-shell/fish-shell" = "4.5.0"
carapace = "1.6.2"
"aqua:nushell/nushell" = "0.110.0"
"cargo:tlrc" = "latest"
